# External Gems
plugins:                    [jekyll-paginate]


# Site Settings
title:                      "Coders Opinion"
email:                      "me@codersopinion.com"
description:                "PHP, CSS, JS, XHTML"
baseurl:                    ""
logourl:                    "/assets/img/bloglogo.jpg"
fa-logo:                    "fa-bookmark-o"
paginate:                   5


# Author Settings
author_name:                "Robert-Jan de Dreu"
author_url:                 "https://codersopinion.com"
author_bio:                 "Hey, I’m Robert-Jan de Dreu. A freelance software engineer, developing software since 2009. While using PHP and Javascript I build well structured and tested software."
author_email:               "me@codersopinion.com"
author_phone:               "+31 6 19 76 61 30"
author_image:               "/assets/img/author.png"

# Social Settings
twitter_url:                "http://twitter.com/robertjandreu"
facebook_url:               ""
github_url:                 "http://github.com/rjd22"
stackoverflow_url:          "https://stackoverflow.com/users/255920/rjd22"
youtube_url:                ""
dribbble_url:               ""
googleplus_url:             ""
instagram_url:              ""
pinterest_url:              ""
linkedin_url:               "http://linkedin.com/in/robertjandedreu"


# Theme Settings
theme_disqus_shortname:     "codersopinion"
theme_google_comments:      false
theme_analytics_id:         ""
theme_reading_time:         true
theme_autoload_comments:    true
theme_always_show_nav:      true


# SASS Settings
# DO NOT MODIFY
sass:
 sass_dir: "assets/css/"
 style: :compressed


# Build Settings
markdown:                   kramdown
permalink:                  pretty

